[project]
name = "upi-fraud-protection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.2.0",
    "matplotlib>=3.10.8",
    "numpy>=2.4.3",
    "pandas>=3.0.2",
    "psycopg2>=2.9.12",
    "pymongo>=4.17.0",
    "python-dotenv>=1.2.3",
    "seaborn>=0.13.2",
    "dnspython",
    "jupyter",
    "jupyter-client",
    "scikit-learn>=1.9.0",
    "feature-engine>=1.9.4",
    "statsmodels>=0.15.0",
    "joblib>=1.6.0",
    "ipynb>=0.5.1",
]
